### ISSUE TITLE
Nasty bug (probably JVM bug)

### ISSUE THREAD

**Issue by sergey-ushakov** [LMAX-Exchange/disruptor#153] opened 2016-04-08 14:59 UTC
Hello!

Recently got strange bug, somehow related to LMAX-Disruptor. 
We managed to create reproducable snapshot: https://github.com/sergey-ushakov/lmax-disruptor-bug

NPE happens in place where it can't happen.
Bug disappears in next cases:
 * JVM started with debugger
 * code changes (see comments in the code):
 * run JVM with -Xint
 * replace publish lambda with anonymous class
 * start test at JDK1.9ea

Bug appears with magic number of processed operations ~110600

Increasing ring buffer at disruptor lowers probality of reproduction. With ring buffer 4 or 8 bug reproduced always.
 
Probably bug related to JIT

**Comment by mikeb01** [comment] 2016-04-09 05:07
Does this occur in any of the stable versions of the JDK e.g. the latest 1.8.

**Comment by sergey-ushakov** [comment] 2016-04-10 11:55
yep, reproducable on:
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by sergey-ushakov** [comment] 2016-04-11 03:45
Note another way to reproduce problem: https://github.com/sergey-ushakov/lmax-disruptor-bug/tree/single-producer
Code simplified to expose publication failures on disruptor with SingleProducerSequencer. Take a look at DisruptorTest

**Comment by mikeb01** [comment] 2016-04-11 04:40
This does look nasty and probably a JVM thing.  I can even remove handler2 by nulling the value out in handler1.

    synchronized // CR
    void testNPE()
    {
        testStarted = System.nanoTime();
        obj.toString();
        obj = null;
        testFinished = System.nanoTime();
    }

Next stop looking at the assembler.  You can also do:

    synchronized // CR
    void publish(long id, Object obj, String str)
    {
        Objects.requireNonNull(obj); // Hides bug

        publishStarted = System.nanoTime();
        this.id = id;
        this.obj = obj;
        this.str = str;
        publishFinished = System.nanoTime();
    }

To fix it.

**Comment by mikeb01** [comment] 2016-04-11 05:00
This is definitely a compiler bug, the field write is being omitted:

The first compile pass is okay, the field 'obj' is being set correctly.

```
  0x00007f27d5191c3a: callq  0x00007f27e94c2dc0  ;*invokestatic nanoTime
                                                ; - disruptorbug.Event::publish@1 (line 41)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ;   {runtime_call}
  0x00007f27d5191c3f: mov    0x50(%rsp),%r8
  0x00007f27d5191c44: mov    %rax,0x18(%r8)     ;*putfield publishStarted
                                                ; - disruptorbug.Event::publish@4 (line 41)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)

  0x00007f27d5191c48: mov    0x58(%rsp),%rsi
  0x00007f27d5191c4d: mov    %rsi,0x10(%r8)     ;*putfield id
                                                ; - disruptorbug.Event::publish@9 (line 42)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)

  0x00007f27d5191c51: mov    0x60(%rsp),%rdx
  0x00007f27d5191c56: mov    %rdx,%r10
  0x00007f27d5191c59: shr    $0x3,%r10
  0x00007f27d5191c5d: mov    %r10d,0xc(%r8)
  0x00007f27d5191c61: mov    %r8,%rsi
  0x00007f27d5191c64: shr    $0x9,%rsi
  0x00007f27d5191c68: mov    $0x7f27d0e3f000,%rdi
  0x00007f27d5191c72: movb   $0x0,(%rsi,%rdi,1)  ;*putfield obj
                                                ; - disruptorbug.Event::publish@14 (line 43)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)

  0x00007f27d5191c76: mov    0x68(%rsp),%rcx
  0x00007f27d5191c7b: mov    %rcx,%r10
  0x00007f27d5191c7e: shr    $0x3,%r10
  0x00007f27d5191c82: mov    %r10d,0x48(%r8)
  0x00007f27d5191c86: mov    %r8,%rsi
  0x00007f27d5191c89: shr    $0x9,%rsi
  0x00007f27d5191c8d: movb   $0x0,(%rsi,%rdi,1)  ;*putfield str
                                                ; - disruptorbug.Event::publish@20 (line 44)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)

  0x00007f27d5191c91: mov    $0x7f27d1846888,%rsi  ;   {metadata(method data for {method} {0x00007f27d1822d88} 'publish' '(JLjava/lang/Object;Ljava/lang/String;)V' in 'disruptorbug/Event')}
  0x00007f27d5191c9b: addq   $0x1,0x118(%rsi)
  0x00007f27d5191ca3: callq  0x00007f27e94c2dc0  ;*invokestatic nanoTime
                                                ; - disruptorbug.Event::publish@24 (line 45)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ;   {runtime_call}
  0x00007f27d5191ca8: mov    0x50(%rsp),%r8
  0x00007f27d5191cad: mov    %rax,0x20(%r8)     ;*putfield publishFinished
                                                ; - disruptorbug.Event::publish@27 (line 45)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
```

However in a later pass the field store is omitted.

```
0x00007f27d51bc3d6: mov    0x20(%rsp),%r10
  0x00007f27d51bc3db: mov    0x50(%rsp),%r11
  0x00007f27d51bc3e0: mov    %r11,0x10(%r10)    ;*putfield id
                                                ; - disruptorbug.Event::publish@9 (line 42)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ; - disruptorbug.DisruptorTest$$Lambda$3/2094548358::translateTo@17
                                                ; - com.lmax.disruptor.RingBuffer::translateAndPublish@7 (line 931)
                                                ; - com.lmax.disruptor.RingBuffer::publishEvent@13 (line 445)
                                                ; - com.lmax.disruptor.dsl.Disruptor::publishEvent@5 (line 256)
                                                ; - disruptorbug.DisruptorTest::test@36 (line 67)

  0x00007f27d51bc3e4: mov    %rax,0x18(%r10)    ;*putfield publishStarted
                                                ; - disruptorbug.Event::publish@4 (line 41)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ; - disruptorbug.DisruptorTest$$Lambda$3/2094548358::translateTo@17
                                                ; - com.lmax.disruptor.RingBuffer::translateAndPublish@7 (line 931)
                                                ; - com.lmax.disruptor.RingBuffer::publishEvent@13 (line 445)
                                                ; - com.lmax.disruptor.dsl.Disruptor::publishEvent@5 (line 256)
                                                ; - disruptorbug.DisruptorTest::test@36 (line 67)

  0x00007f27d51bc3e8: movl   $0xe3443032,0x48(%r10)  ;   {oop("str")}
  0x00007f27d51bc3f0: shr    $0x9,%r10
  0x00007f27d51bc3f4: mov    $0x7f27d0e3f000,%r11
  0x00007f27d51bc3fe: mov    %r12b,(%r11,%r10,1)  ;*putfield str
                                                ; - disruptorbug.Event::publish@20 (line 44)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ; - disruptorbug.DisruptorTest$$Lambda$3/2094548358::translateTo@17
                                                ; - com.lmax.disruptor.RingBuffer::translateAndPublish@7 (line 931)
                                                ; - com.lmax.disruptor.RingBuffer::publishEvent@13 (line 445)
                                                ; - com.lmax.disruptor.dsl.Disruptor::publishEvent@5 (line 256)
                                                ; - disruptorbug.DisruptorTest::test@36 (line 67)

  0x00007f27d51bc402: mov    $0x7f27e94c2dc0,%r10
  0x00007f27d51bc40c: callq  *%r10              ;*invokestatic nanoTime
                                                ; - disruptorbug.Event::publish@24 (line 45)
                                                ; - disruptorbug.DisruptorTest::lambda$test$0@5 (line 68)
                                                ; - disruptorbug.DisruptorTest$$Lambda$3/2094548358::translateTo@17
                                                ; - com.lmax.disruptor.RingBuffer::translateAndPublish@7 (line 931)
                                                ; - com.lmax.disruptor.RingBuffer::publishEvent@13 (line 445)
                                                ; - com.lmax.disruptor.dsl.Disruptor::publishEvent@5 (line 256)
                                                ; - disruptorbug.DisruptorTest::test@36 (line 67)
```

**Comment by mikeb01** [comment] 2016-04-11 05:00
I'll raise a bug on the JDK bug tracker.  Good spot.

**Comment by mikeb01** [comment] 2016-04-11 05:25
I've raised the bug with Oracle, will post link to bug details when I get them.

**Comment by codeaholics** [comment] 2016-04-11 07:19
Would it be a good idea to have some kind of start-up test in the disruptor which warns if it detects a known-bad JVM? Otherwise this might bite future users in subtle ways that they don't notice.

**Comment by mikeb01** [comment] 2016-04-11 08:13
Given that this fails on the 2 most recent releases of the JDK8 (60 & 77) then it is probably not that useful.  So even at LMAX we would just ignore the warning.

**Comment by mikeb01** [comment] 2016-04-12 07:52
Looks like this is a duplicate of an existing bug (https://bugs.openjdk.java.net/browse/JDK-8153980) and and fixed in b102.  I'll check with that version and if it works will close the bug.

**Comment by mikeb01** [comment] 2016-04-12 08:04
Confirmed that this works okay on jdk8 b102.

**Closed by mikeb01** 2016-04-12 08:04 UTC

**Comment by sergey-ushakov** [comment] 2016-04-12 08:30
Cool. Thank you!
