### ISSUE TITLE
Increased CPU Time caused by TimeoutBlockingWaitStrategy

### ISSUE THREAD

**Issue by CanGokdere** [LMAX-Exchange/disruptor#358] opened 2021-03-27 19:41 UTC
Hello, I have been using disruptor (3.3.x) with log4j (2.6) in my project.
Recently, I have upgraded to log4j 2.14 and disruptor 3.4.2. I am using default values.

After the upgrade, I have profiled my CPU cycles and found out that:

TimeoutBlockingWaitStrategy.waitFor() jumped from %0.1 to ~%8, roughly 80 times slower.

My best guess is, this is caused by the following commit:
https://github.com/LMAX-Exchange/disruptor/commit/a18f8198ab94590f0a5ec7c3378ba87f997ea670#diff-06ba76f327d4242a110faf85be993d61f45b9e1df4364fb193330980970423ad

Any suggestions or workaround to tackle this problem ?
Thanks a lot

**Comment by A248** [comment] 2021-03-30 12:06
Note that disruptor 3.4.2 was released on April 8, 2018, whereas that commit is from April 23. So, I do not think such commit is the cause of your CPU issue.

**Comment by CanGokdere** [comment] 2021-03-30 12:10
@A248 It says 3.4.2 is released this on Sep 2, 2018. 
Besides of the dates, I inspected the stack trace I can see follow up functions in that commit:
Utils.awaitNanos and Object.wait 
which was not there before I did the upgrade

**Comment by ennerf** [comment] 2021-03-30 12:57
In case you're testing on Windows, be aware that `sleep / wait / park` were significantly impacted by Java 14 as well as some undocumented changes in build `19041`. Below are some jHiccup-like results from our internal tests in case it's relevant for anyone. Linux didn't change significantly between versions.

Windows 18362

![windows10_18362](https://user-images.githubusercontent.com/5491587/112990790-ba1bae00-9166-11eb-9716-f2925b2208d6.png)

Windows 19041

![windows10_19041_sleep](https://user-images.githubusercontent.com/5491587/112990829-c56ed980-9166-11eb-9afa-f831539e982c.png)

Zulu 13

![win10_j13](https://user-images.githubusercontent.com/5491587/112990954-e9321f80-9166-11eb-90bf-767ab70c73df.png)

Zulu 14

![win10_j14](https://user-images.githubusercontent.com/5491587/112990961-ec2d1000-9166-11eb-9781-c5bec41e0f04.png)

Zulu 15

![win10_j15](https://user-images.githubusercontent.com/5491587/112991336-4928c600-9167-11eb-921a-01d35e6841ea.png)

**Comment by CanGokdere** [comment] 2021-03-30 15:41
Hello, I am back with more stats. I have not mentioned OS and Java version sorry about that:
My server is working on AmazonLinux2012 with Java8.

So a bit more stats for before and after:
Before upgrade, call stack summary

com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor
Total CPU Time: 0.3% || Thread Idle: 99.9%

java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos: 
Total CPU Time: 0.3% || Thread Idle: 100%

java.util.concurrent.locks.LockSupport.parkNanos: 
Total CPU Time: 0.3% || Thread Idle: 100%

sun.misc.Unsafe.park: 
Total CPU Time: 0.3% || Thread Idle: 100%

-----------------------------------------------------------
After upgrade, call stack summary

com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor
Total CPU Time: 7.4% || Thread Timed waiting: 98.5% Runnable: 1.3% Blocked: 0.1

com.lmax.disruptor.util.Util.awaitNanos
Total CPU Time: 7.3% || Thread Timed waiting: 98.5% Runnable: 1.3% Blocked: 0.1

java.lang.Object.wait
Total CPU Time: 7.3% || Thread Timed waiting: 98.5% Runnable: 1.3% Blocked: 0.1

java.lang.Object.wait
Total CPU Time: 7.3% || Thread Timed waiting: 98.5% Runnable: 1.3% Blocked: 0.1

**Comment by Palmr** [comment] 2021-03-30 17:29
What profiler are you using?

I know that some profilers understand `sun.misc.Unsafe.park` better and that the CPU is idle during the time parked.
They don't all understand that during `java.lang.Object.wait` the CPU is effectively idle too and might show CPU time as the time between entering that function and it returning.
See: https://stackoverflow.com/questions/8656912/cpu-usage-and-object-wait and similar discussions online.

In your stats you posted I see the information is different between runs. the first show CPU Time and Thread Idle %, the second set shows CPU time being high, but also that it was Thread Timed waiting almost all of that time and barely Runnable.

Let us know what profiler you are using and perhaps try another to compare notes?

**Comment by CanGokdere** [comment] 2021-04-26 14:29
Hello @Palmr sorry for the delayed response.

The profiler is using JVM ThreadMXBean to capture the thread info and state.

**Comment by Palmr** [comment] 2021-12-30 11:00
As far as I can tell, no benchmark or reproducible test case has been forthcoming here.
I had a go myself and could not reproduce the result posted.

I might chalk this up to being a profiling method that doesn't understand `Object.wait`, and I'm going to close this issue unless there's a reproducible test case to run.

**Closed by Palmr** 2021-12-30 11:00 UTC
Labels: performance
