### ISSUE TITLE
ThreadHints.onSpinWait() in BlockingWaitStrategy cause high cpu load sometimes

### ISSUE THREAD

**Issue by KaimingWan** [LMAX-Exchange/disruptor#359] opened 2021-03-31 03:11 UTC
We use disruptor 3.4.2 and find sometimes the cpu load goes very high and the jstack show that the thread is invoking ThreadHints.onSpinWait() in BlockingWaitStrategy. Now we implement a custom BlockingWaitStrategy and remove this code.

**Comment by KaimingWan** [comment] 2021-03-31 04:08
Is the following code still will cause high cpu load?  Thread invoke barrier.checkAlert() will occupy cpu for long time. I think this will also cause high cpu load. Am I right?

```java
        while ((availableSequence = dependentSequence.get()) < sequence)
        {
            barrier.checkAlert();
        }
```

**Comment by Palmr** [comment] 2021-06-16 11:47
I think this is a duplicate of #358 so closing this issue as more discussion happened there already.

**Closed by Palmr** 2021-06-16 11:47 UTC
Labels: duplicate
