### ISSUE TITLE
Concurrency safe with multiple producers and consumers

### ISSUE THREAD

**Issue by Veryfirefly** [LMAX-Exchange/disruptor#423] opened 2022-06-07 09:45 UTC
**Describe the bug**
When I use multi-producer and multi-consumer, the accumulator does not always achieve what I expect. But the next method of MultiProducerSequencer is thread safe. I don't know the cause of the problem, can you help me?

**To Reproduce**
``` java

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Stream;

import com.lmax.disruptor.EventFactory;
import com.lmax.disruptor.ExceptionHandler;
import com.lmax.disruptor.RingBuffer;
import com.lmax.disruptor.SleepingWaitStrategy;
import com.lmax.disruptor.TimeoutException;
import com.lmax.disruptor.WorkHandler;
import com.lmax.disruptor.dsl.Disruptor;
import com.lmax.disruptor.dsl.ProducerType;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import utils.NamedProducerThreadFactory;

public class DisruptorConcurrencySafeTests {

	private static final int RING_BUFFER_SIZE = 2 << 16;
	private static final int DEFAULT_CORE_NUM = 2;
	private static final int LOOP_COUNT = 1000_0000;

	static class ConcurrencySafeBean {

		private String identifier;
		private Long value;

		ConcurrencySafeBean() {

		}

		static ConcurrencySafeBean createDefault() {
			return new ConcurrencySafeBean();
		}

		public String getIdentifier() {
			return identifier;
		}

		public void setIdentifier(String identifier) {
			this.identifier = identifier;
		}

		public Long getValue() {
			return value;
		}

		public void setValue(Long value) {
			this.value = value;
		}
	}

	static class ConcurrencySafeBeanFactory implements EventFactory<ConcurrencySafeBean> {

		@Override
		public ConcurrencySafeBean newInstance() {
			return ConcurrencySafeBean.createDefault();
		}
	}

	static class ConcurrencySafeBeanWorkHandler implements WorkHandler<ConcurrencySafeBean> {

		private final AtomicLong accumulator;

		public ConcurrencySafeBeanWorkHandler(AtomicLong accumulator) {
			this.accumulator = accumulator;
		}

		@Override
		public void onEvent(ConcurrencySafeBean event) throws Exception {
			accumulator.addAndGet(event.getValue());
		}
	}

	static class DefaultExceptionHandler implements ExceptionHandler<ConcurrencySafeBean> {

		@Override
		public void handleEventException(Throwable ex, long sequence, ConcurrencySafeBean event) {
			System.err.println("[HandleEventException] the exception cause: "
					+ ex.getMessage() + ", sequence: " + sequence);
		}

		@Override
		public void handleOnStartException(Throwable ex) {
			System.err.println("[HandleOnStartException] the exception cause: " + ex.getMessage());
		}

		@Override
		public void handleOnShutdownException(Throwable ex) {
			System.err.println("[HandleOnShutdownException] the exception cause: " + ex.getMessage());
		}
	}

	private Disruptor<ConcurrencySafeBean> safeDisruptor;
	private Disruptor<ConcurrencySafeBean> unsafeDisruptor;
	private RingBuffer<ConcurrencySafeBean> safeRingBuffer;
	private RingBuffer<ConcurrencySafeBean> unsafeRingBuffer;

	private final AtomicLong safeAccumulator = new AtomicLong(0L);
	private final AtomicLong unsafeAccumulator = new AtomicLong(0L);

	@Before
	public void initialize() {
		initSafeDisruptor();
		initUnsafeDisruptor();
	}

	@After
	public void destroyed() {
		try {
			safeDisruptor.shutdown(10, TimeUnit.SECONDS);
			unsafeDisruptor.shutdown(10, TimeUnit.SECONDS);
		}
		catch (TimeoutException e) {
			throw new RuntimeException(e);
		}
	}

	@Test
	public void testSingleProducerAndMultiConsumersCases() {
		final CountDownLatch shutdownLatch = new CountDownLatch(DEFAULT_CORE_NUM);
		ThreadGroup threadGroup = new ThreadGroup("Unsafe-Concurrency-ThreadGroup");
		Thread[] producerThreads = createProducerThreads(
				threadGroup,
				"Unsafe-Consumer-Thread-",
				() -> {
					for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
						long sequence = unsafeRingBuffer.next(1);
						try {
							ConcurrencySafeBean csb = unsafeRingBuffer.get(sequence);
							csb.setIdentifier("Unsafe concurrency bean");
							csb.setValue(1L);
						}
						finally {
							unsafeRingBuffer.publish(sequence);
						}
					}
					shutdownLatch.countDown();
				},
				DEFAULT_CORE_NUM
		);
		Stream.of(producerThreads)
			.forEach(Thread::start);

		try {
			shutdownLatch.await();
		}
		catch (InterruptedException e) {
			// NOOP
		}

		System.out.println("[Unsafe Concurrency] accumulator: " + unsafeAccumulator.get());

		threadGroup.interrupt();
	}

	@Test
	public void testMultiProducersAndMultiConsumersCases() {
		final CountDownLatch shutdownLatch = new CountDownLatch(DEFAULT_CORE_NUM);
		ThreadGroup threadGroup = new ThreadGroup("Safe-Concurrency-ThreadGroup");
		Thread[] producerThreads = createProducerThreads(
				threadGroup,
				"Safe-Consumer-Thread-",
				() -> {
					for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
						long sequence = safeRingBuffer.next(1);
						try {
							ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
							csb.setIdentifier("Safe concurrency bean");
							csb.setValue(1L);
						}
						finally {
							safeRingBuffer.publish(sequence);
						}
					}
					shutdownLatch.countDown();
				},
				DEFAULT_CORE_NUM
		);
		Stream.of(producerThreads)
				.forEach(Thread::start);

		try {
			shutdownLatch.await();
		}
		catch (InterruptedException e) {
			// NOOP
		}

		System.out.println("[Safe Concurrency] accumulator: " + safeAccumulator.get());

		threadGroup.interrupt();
	}

	private void initSafeDisruptor() {
		this.safeDisruptor = new Disruptor<>(
				new ConcurrencySafeBeanFactory(),
				RING_BUFFER_SIZE,
				new NamedProducerThreadFactory("safe-disruptor-processor-", ""),
				ProducerType.MULTI,
				new SleepingWaitStrategy()
		);

		WorkHandler<ConcurrencySafeBean>[] workHandlers = createWorkHandler(DEFAULT_CORE_NUM, safeAccumulator);
		this.safeDisruptor.handleEventsWithWorkerPool(workHandlers);
		this.safeDisruptor.setDefaultExceptionHandler(new DefaultExceptionHandler());
		this.safeDisruptor.start();

		this.safeRingBuffer = safeDisruptor.getRingBuffer();
	}

	private void initUnsafeDisruptor() {
		this.unsafeDisruptor = new Disruptor<>(
				new ConcurrencySafeBeanFactory(),
				RING_BUFFER_SIZE,
				new NamedProducerThreadFactory("safe-disruptor-processor-", ""),
				ProducerType.SINGLE,
				new SleepingWaitStrategy()
		);

		WorkHandler<ConcurrencySafeBean>[] workHandlers = createWorkHandler(DEFAULT_CORE_NUM, unsafeAccumulator);
		this.unsafeDisruptor.handleEventsWithWorkerPool(workHandlers);
		this.unsafeDisruptor.setDefaultExceptionHandler(new DefaultExceptionHandler());
		this.unsafeDisruptor.start();

		this.unsafeRingBuffer = unsafeDisruptor.getRingBuffer();
	}

	protected WorkHandler<ConcurrencySafeBean>[] createWorkHandler(
			final int coreNum, final AtomicLong atomicAccumulator) {
		WorkHandler<ConcurrencySafeBean>[] workHandlers = new ConcurrencySafeBeanWorkHandler[coreNum];
		for (int accumulator = 0; accumulator < coreNum; accumulator++) {
			workHandlers[accumulator] = new ConcurrencySafeBeanWorkHandler(atomicAccumulator);
		}
		return workHandlers;
	}

	protected Thread[] createProducerThreads(
			final ThreadGroup group,
			final String threadName,
			final Runnable runnable,
			final int coreNum
	) {
		int threadNumber = 0;
		Thread[] threads = new Thread[coreNum];
		for (int i = 0; i < coreNum; i++) {
			threads[i] = new Thread(
					group,
					runnable,
					threadName + threadNumber
			);
			threadNumber ++;
		}
		return threads;
	}

}

```

**Expected behavior**
In the case of multiple producers and consumers, the expected value of safeAccumulator should be 10000000, but not always.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 3.4.4
 - JVM Version: Oracle JDK 1.8

**Additional context**
I found the problem of sequence repetition in the mode of single producer and multi-consumer, and found the problem by switching to the mode of multi-producer and multi-consumer. The sample code is a verification of the problem occurring on the line. This sample code was not tested on the Linux platform.

**Comment by SteafanMrZhou** [comment] 2022-06-10 03:06
Hi,Can you provide the NamedProducerThreadFactory method,we need to reproduce this problem.

**Comment by Veryfirefly** [comment] 2022-06-13 06:30
> Hi,Can you provide the NamedProducerThreadFactory method,we need to reproduce this problem. In addition,the code line `threadGroup.interrupt();`Why do you have to manually interrupt the thread group？ According to the Happens-Before rules,in `testMultiProducersAndMultiConsumersCases` method,There is no strict logical relationship between each line of code,So, may be optimized by JVM. We need the NamedProducerThreadFactory method or complete code to reproduce this problem.

Hi, this is my `NamedProducerThreadFactory` code.

``` java

public class NamedProducerThreadFactory implements ThreadFactory {

	private final AtomicInteger threadNumber = new AtomicInteger(1);

	private final String threadPrefix;
	private final String threadSuffix;

	public NamedProducerThreadFactory(String threadPrefix, String threadSuffix) {
		this.threadPrefix = threadPrefix;
		this.threadSuffix = threadSuffix;
	}

	@Override
	public Thread newThread(Runnable r) {
		Thread t = new Thread(r, threadPrefix + threadNumber.getAndIncrement() + threadSuffix);
		if (t.getPriority() < Thread.NORM_PRIORITY) {
			t.setPriority(Thread.NORM_PRIORITY);
		}
		return t;
	}
}

```

The code snippet threadGroup.interrupt() is really redundant. When writing the test code, I ignored the problem that the thread will automatically exit when the task execution is completed.

Thank you very much for pointing out the cause of the problem (may be caused by the optimization of the code by the happens-before rule), and I am currently looking for the problem in this direction.

**Comment by SteafanMrZhou** [comment] 2022-06-13 09:29
By debugging the code you provided, it took me two hours to solve your problem. For space reasons, I made a gif image of the final result of the successful modification. Let's look at the final effect first:
![Disruptor-Fix-Issue-#423_](https://user-images.githubusercontent.com/23360739/173323549-5d3749a5-b5ca-4dca-8b3d-3cbcc44bf146.gif)
After solving the problem, I manually tested the `testMultiProducersAndMultiConsumersCases` method and executed it 5 times manually, and the result of each manual execution was exactly the 10000000 you expected.

**Comment by SteafanMrZhou** [comment] 2022-06-13 09:34
and NamedProducerThreadFactory method is nothing about the question.

**Comment by Veryfirefly** [comment] 2022-06-13 12:17
> For this code, your main problem is memory visibility of variables and synchronization issues when compounding on ringBuffer.
> 
> I will release the modified code first. If I have time, I will write a detailed analysis of the thread safety of this code. If there is any unclear place, please leave a message.
> 
> package com.steafan.concurrent.disruptor.issue;
> 
> import com.lmax.disruptor.*; import com.lmax.disruptor.dsl.Disruptor; import com.lmax.disruptor.dsl.ProducerType; import org.junit.After; import org.junit.Before; import org.junit.Test;
> 
> import java.util.concurrent.CountDownLatch; import java.util.concurrent.TimeUnit; import java.util.concurrent.atomic.AtomicInteger; import java.util.concurrent.atomic.AtomicLong; import java.util.stream.Stream;
> 
> public class DisruptorConcurrencySafeTests {
> 
> ```
> private static final int RING_BUFFER_SIZE = 2 << 16;
> private static final int DEFAULT_CORE_NUM = 2;
> private static final int LOOP_COUNT = 1000_0000;
> 
> static class ConcurrencySafeBean {
> 
>     private volatile String identifier;
>     private volatile Long value;
> 
>     ConcurrencySafeBean() {
> 
>     }
> 
>     static ConcurrencySafeBean createDefault() {
>         return new ConcurrencySafeBean();
>     }
> 
>     public String getIdentifier() {
>         return identifier;
>     }
> 
>     public void setIdentifier(String identifier) {
>         this.identifier = identifier;
>     }
> 
>     public Long getValue() {
>         return value;
>     }
> 
>     public void setValue(Long value) {
>         this.value = value;
>     }
> }
> 
> static class ConcurrencySafeBeanFactory implements EventFactory<ConcurrencySafeBean> {
> 
>     @Override
>     public ConcurrencySafeBean newInstance() {
>         return ConcurrencySafeBean.createDefault();
>     }
> }
> 
> static class ConcurrencySafeBeanWorkHandler implements WorkHandler<ConcurrencySafeBean> {
> 
>     private final AtomicLong accumulator;
> 
>     public ConcurrencySafeBeanWorkHandler(AtomicLong accumulator) {
>         this.accumulator = accumulator;
>     }
> 
>     @Override
>     public void onEvent(ConcurrencySafeBean event) throws Exception {
>         accumulator.addAndGet(event.getValue());
>     }
> }
> 
> static class DefaultExceptionHandler implements ExceptionHandler<ConcurrencySafeBean> {
> 
>     @Override
>     public void handleEventException(Throwable ex, long sequence, ConcurrencySafeBean event) {
>         System.err.println("[HandleEventException] the exception cause: "
>                 + ex.getMessage() + ", sequence: " + sequence);
>     }
> 
>     @Override
>     public void handleOnStartException(Throwable ex) {
>         System.err.println("[HandleOnStartException] the exception cause: " + ex.getMessage());
>     }
> 
>     @Override
>     public void handleOnShutdownException(Throwable ex) {
>         System.err.println("[HandleOnShutdownException] the exception cause: " + ex.getMessage());
>     }
> }
> 
> private Disruptor<ConcurrencySafeBean> safeDisruptor;
> private Disruptor<ConcurrencySafeBean> unsafeDisruptor;
> private RingBuffer<ConcurrencySafeBean> safeRingBuffer;
> private RingBuffer<ConcurrencySafeBean> unsafeRingBuffer;
> 
> private final AtomicLong safeAccumulator = new AtomicLong(0L);
> private final AtomicLong unsafeAccumulator = new AtomicLong(0L);
> 
> @Before
> public void initialize() {
>     initSafeDisruptor();
>     initUnsafeDisruptor();
> }
> 
> @After
> public void destroyed() {
>     try {
>         safeDisruptor.shutdown(10, TimeUnit.SECONDS);
>         unsafeDisruptor.shutdown(10, TimeUnit.SECONDS);
>     } catch (TimeoutException e) {
>         throw new RuntimeException(e);
>     }
> }
> 
> @Test
> public void testSingleProducerAndMultiConsumersCases() {
>     final CountDownLatch shutdownLatch = new CountDownLatch(DEFAULT_CORE_NUM);
>     ThreadGroup threadGroup = new ThreadGroup("Unsafe-Concurrency-ThreadGroup");
>     Thread[] producerThreads = createProducerThreads(
>             threadGroup,
>             "Unsafe-Consumer-Thread-",
>             () -> {
>                 for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
>                     long sequence = unsafeRingBuffer.next(1);
>                     try {
>                         ConcurrencySafeBean csb = unsafeRingBuffer.get(sequence);
>                         csb.setIdentifier("Unsafe concurrency bean");
>                         csb.setValue(1L);
>                     } finally {
>                         unsafeRingBuffer.publish(sequence);
>                     }
>                 }
>                 shutdownLatch.countDown();
>             },
>             DEFAULT_CORE_NUM
>     );
>     Stream.of(producerThreads)
>             .forEach(Thread::start);
> 
>     try {
>         shutdownLatch.await();
>     } catch (InterruptedException e) {
>         // NOOP
>     }
> 
>     System.out.println("[Unsafe Concurrency] accumulator: " + unsafeAccumulator.get());
> 
>     threadGroup.interrupt();
> }
> 
> @Test
> public void testMultiProducersAndMultiConsumersCases() {
>     final CountDownLatch shutdownLatch = new CountDownLatch(DEFAULT_CORE_NUM);
>     ThreadGroup threadGroup = new ThreadGroup("Safe-Concurrency-ThreadGroup");
>     Thread[] producerThreads = createProducerThreads(
>             threadGroup,
>             "Safe-Consumer-Thread-",
>             new Runnable() {
>                 @Override
>                 public void run() {
>                     for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
>                         long sequence = safeRingBuffer.next(1);
> ```
> 
> // try { synchronized (safeRingBuffer) { ConcurrencySafeBean csb = safeRingBuffer.get(sequence); csb.setIdentifier("Safe concurrency bean"); csb.setValue(1L); safeRingBuffer.publish(sequence); } // } finally { // // } }
> 
> ```
>                     shutdownLatch.countDown();
>                 }
>             },
>             DEFAULT_CORE_NUM
>     );
> 
>     for (Thread thread : producerThreads) {
>         synchronized (DisruptorConcurrencySafeTests.class) {
>             thread.start();
>         }
>     }
> ```
> 
> // Stream.of(producerThreads) // .forEach(Thread::start); try { shutdownLatch.await(); } catch (InterruptedException e) { // NOOP System.out.println("123"); }
> 
> ```
>     System.out.println("[Safe Concurrency] accumulator: " + safeAccumulator.get());
> ```
> 
> // threadGroup.interrupt(); }
> 
> ```
> private void initSafeDisruptor() {
> 
>     this.safeDisruptor = new Disruptor<>(
>             new ConcurrencySafeBeanFactory(),
>             RING_BUFFER_SIZE,
>             new NamedProducerThreadFactory("safe-disruptor-processor-", ""),
>             ProducerType.MULTI,
>             new SleepingWaitStrategy()
>     );
>     WorkHandler<ConcurrencySafeBean>[] workHandlers = createWorkHandler(DEFAULT_CORE_NUM, safeAccumulator);
>     this.safeDisruptor.handleEventsWithWorkerPool(workHandlers);
>     this.safeDisruptor.setDefaultExceptionHandler(new DefaultExceptionHandler());
>     this.safeDisruptor.start();
> 
>     this.safeRingBuffer = this.safeDisruptor.getRingBuffer();
> }
> 
> private void initUnsafeDisruptor() {
>     this.unsafeDisruptor = new Disruptor<>(
>             new ConcurrencySafeBeanFactory(),
>             RING_BUFFER_SIZE,
>             new NamedProducerThreadFactory("safe-disruptor-processor-", ""),
>             ProducerType.SINGLE,
>             new SleepingWaitStrategy()
>     );
>     WorkHandler<ConcurrencySafeBean>[] workHandlers = createWorkHandler(DEFAULT_CORE_NUM, unsafeAccumulator);
>     this.unsafeDisruptor.handleEventsWithWorkerPool(workHandlers);
>     this.unsafeDisruptor.setDefaultExceptionHandler(new DefaultExceptionHandler());
>     this.unsafeDisruptor.start();
> 
>     this.unsafeRingBuffer = this.unsafeDisruptor.getRingBuffer();
> }
> 
> protected WorkHandler<ConcurrencySafeBean>[] createWorkHandler(
>         final int coreNum, final AtomicLong atomicAccumulator) {
>     WorkHandler<ConcurrencySafeBean>[] workHandlers = new ConcurrencySafeBeanWorkHandler[coreNum];
>     for (int accumulator = 0; accumulator < coreNum; accumulator++) {
>         workHandlers[accumulator] = new ConcurrencySafeBeanWorkHandler(atomicAccumulator);
>     }
>     return workHandlers;
> }
> 
> protected Thread[] createProducerThreads(
>         final ThreadGroup group,
>         final String threadName,
>         final Runnable runnable,
>         final int coreNum
> ) {
>     AtomicInteger threadNumber = new AtomicInteger(0);
>     Thread[] threads = new Thread[coreNum];
>     for (int i = 0; i < coreNum; i++) {
>         threads[i] = new Thread(
>                 group,
>                 runnable,
>                 threadName + threadNumber
>         );
>         threadNumber.incrementAndGet();
>     }
>     return threads;
> }
> ```
> 
> }

I copied your code and created a new package with the same name for testing, but the result did not meet expectations. The result of repeated testing on my colleague's computer is correct.

![ConcurrencyTests.java_GIF](https://xsdq.xyz/base_logserver_mobilegame_DisruptorConcurrencySafeTests.java.gif)

**Comment by Veryfirefly** [comment] 2022-06-13 12:20
> By debugging the code you provided, it took me two hours to solve your problem. For space reasons, I made a gif image of the final result of the successful modification. Let's look at the final effect first: ![Disruptor-Fix-Issue-#423_](https://user-images.githubusercontent.com/23360739/173323549-5d3749a5-b5ca-4dca-8b3d-3cbcc44bf146.gif) [ ](https://user-images.githubusercontent.com/23360739/173323549-5d3749a5-b5ca-4dca-8b3d-3cbcc44bf146.gif) ![Disruptor-Fix-Issue-#423_](https://user-images.githubusercontent.com/23360739/173323549-5d3749a5-b5ca-4dca-8b3d-3cbcc44bf146.gif) [ ](https://user-images.githubusercontent.com/23360739/173323549-5d3749a5-b5ca-4dca-8b3d-3cbcc44bf146.gif) After solving the problem, I manually tested the `testMultiProducersAndMultiConsumersCases` method and executed it 5 times manually, and the result of each manual execution was exactly the 10000000 you expected.

This is my test result
![base_logserver_mobilegame – issue_DisruptorConcurrencySafeTests java 2022-06-13 17-49-42](https://user-images.githubusercontent.com/20528475/173352191-6772ce0d-174f-40ca-8c10-853ac69a493d.gif)

**Comment by Veryfirefly** [comment] 2022-06-13 12:40
> and NamedProducerThreadFactory method is nothing about the question.

I replaced jdk1.8 with 11 and the result still did not meet expectations.

Then I modified the following code snippet

``` java

for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
    long sequence = safeRingBuffer.next(1);
    synchronized (safeRingBuffer) {
        ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
        csb.setIdentifier("Safe concurrency bean");
        csb.setValue(1L);
        safeRingBuffer.publish(sequence);
    }
}

```

to

``` java

for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
	long sequence = safeRingBuffer.next(1);
	ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
	synchronized (csb) {
		csb.setIdentifier("Safe concurrency bean");
		csb.setValue(1L);
		safeRingBuffer.publish(sequence);
	}
}

```

The expected value is reached progressively more times, but this is still problematic.

Here is my modified test result

![base_logserver_mobilegame – issue_DisruptorConcurrencySafeTests java 2022-06-13 20-24-13](https://user-images.githubusercontent.com/20528475/173354459-b5f29a72-098a-44dc-b91a-a56e6958ce20.gif)

Since my colleague ran the same code and the results were correct, I started to suspect that it was my hardware.

I have a doubt about `RingBuffer`, 

The `Sequencer` created by `Producer.MULTI` is `MultiProducerSequencer`. This componet uses the Unsafe class to ensure thread safety when executing the `next(int num)` method, so why do we add `synchronized` to `safeRingBuffer`?

Is it because when assigning a value to a bean, the assignment fails due to a cpu interrupt problem?

**Comment by Veryfirefly** [comment] 2022-06-14 02:13
@SteafanMrZhou Hi SteafanMrZhou! I tested it in the idea versions 2019.1, 2021.2 and 2022.1, and the result values on the 2019.1 version can always meet expectations (Maybe I didn't test it enough).
So I suspect that the problem lies in the process of IDEA calling the junit test method. I use the `mvn clean test -Dtest=com.steafan.concurrent.disruptor.issue.DisruptorConcurrencySafeTests` command to perform unit tests, and after running it several times, I still get incorrect results (so the problem may not be here :worried: ).
What is your idea version please? Can you execute the above maven test command a few times? Thanks!

![mvn_test_command](https://user-images.githubusercontent.com/20528475/173478275-8f34e9d2-ea05-4ef6-b208-338cd6f38590.png)

The result value of my colleague A's test:

![colleague_A's_1655170442697](https://user-images.githubusercontent.com/20528475/173478414-b94412ce-5ad6-45d9-ae8b-db87d6bde267.png)

The result value of my colleague B's test:

![colleague_B's_16551713914311](https://user-images.githubusercontent.com/20528475/173478511-e76662ad-c09e-41a5-a609-ce4026d61687.png)

Thank you very much for your help.

**Comment by SteafanMrZhou** [comment] 2022-06-14 02:18
> > and NamedProducerThreadFactory method is nothing about the question.
> 
> I replaced jdk1.8 with 11 and the result still did not meet expectations.
> 
> Then I modified the following code snippet
> 
> ```java
> for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
>     long sequence = safeRingBuffer.next(1);
>     synchronized (safeRingBuffer) {
>         ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
>         csb.setIdentifier("Safe concurrency bean");
>         csb.setValue(1L);
>         safeRingBuffer.publish(sequence);
>     }
> }
> ```
> 
> to
> 
> ```java
> for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
> 	long sequence = safeRingBuffer.next(1);
> 	ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
> 	synchronized (csb) {
> 		csb.setIdentifier("Safe concurrency bean");
> 		csb.setValue(1L);
> 		safeRingBuffer.publish(sequence);
> 	}
> }
> ```
> 
> The expected value is reached progressively more times, but this is still problematic.
> 
> Here is my modified test result
> 
> ![base_logserver_mobilegame – issue_DisruptorConcurrencySafeTests java 2022-06-13 20-24-13](https://user-images.githubusercontent.com/20528475/173354459-b5f29a72-098a-44dc-b91a-a56e6958ce20.gif) [ ](https://user-images.githubusercontent.com/20528475/173354459-b5f29a72-098a-44dc-b91a-a56e6958ce20.gif) ![base_logserver_mobilegame – issue_DisruptorConcurrencySafeTests java 2022-06-13 20-24-13](https://user-images.githubusercontent.com/20528475/173354459-b5f29a72-098a-44dc-b91a-a56e6958ce20.gif) [ ](https://user-images.githubusercontent.com/20528475/173354459-b5f29a72-098a-44dc-b91a-a56e6958ce20.gif)
> 
> Since my colleague ran the same code and the results were correct, I started to suspect that it was my hardware.
> 
> I have a doubt about `RingBuffer`,
> 
> The `Sequencer` created by `Producer.MULTI` is `MultiProducerSequencer`. This componet uses the Unsafe class to ensure thread safety when executing the `next(int num)` method, so why do we add `synchronized` to `safeRingBuffer`?
> 
> Is it because when assigning a value to a bean, the assignment fails due to a cpu interrupt problem?

RingBuffer itself is thread-safe, but combined with your code context, it is not thread-safe, because your code logic does not guarantee thread safety when using RingBuffer in combination.

**Comment by SteafanMrZhou** [comment] 2022-06-14 02:22
> 

My Idea version is 2020.1.3 and this question has nothing to do with that.

**Comment by Veryfirefly** [comment] 2022-06-14 02:32
> 

Yes, I also had inconsistent results when I tested it on another colleague's machine. His IDEA version is 2019.3.

**Comment by Veryfirefly** [comment] 2022-06-14 02:33
> > 
> 
> My Idea version is 2020.1.3 and this question has nothing to do with this.

Yes, I also had inconsistent results when I tested it on another colleague's machine. His IDEA version is 2019.3.

**Comment by SteafanMrZhou** [comment] 2022-06-14 02:40
The thread-safe question is assoicated with code and hardware.
For programmers, considering thread safety issues should first consider the code level, and finally consider the impact of hardware devices.
For your code, your main problem is memory visibility of variables and synchronization issues when compounding on ringBuffer:
1. The `ConcurrencySafeBean ` class is invisible to other threads,therefore, by modifying the visibility of the fields of this class, the class can be modified to be memory-visible.
2. About synchronized:
```
for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
	long sequence = safeRingBuffer.next(1);
	try {
	          ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
		  csb.setIdentifier("Safe concurrency bean");
		  csb.setValue(1L);
	     } finally {
		  safeRingBuffer.publish(sequence);
	     }
}
```
In this code segment,the `safeRingBuffer` is not thread safe,because you can't guarantee that there is only one thread at the same time when you get the value from safeRingBuffer, you need to add synchronization here.
For `sequence` field,this variable is a local variable, and its thread safety is realized by enclosing it in the method, that is, in the form of thread closing, so it will not overflow when it is released, so for this variable, it is thread safety.
```
 for (int i = 0; i < LOOP_COUNT / DEFAULT_CORE_NUM; i++) {
    long sequence = safeRingBuffer.next(1);
    synchronized (safeRingBuffer) {
        ConcurrencySafeBean csb = safeRingBuffer.get(sequence);
        csb.setIdentifier("Safe concurrency bean");
        csb.setValue(1L);
        safeRingBuffer.publish(sequence);
    }
}
```
Other places where the synchronized keyword is used are for this reason.

For hardware, it should be mainly considered from the perspective of the CPU used, and whether the version or number of cores of the CPU used is the same, which is also a secondary factor affecting thread computing.

Your code problems are mainly these points, other factors will not directly affect the thread safety of your code.

**Closed** 2022-06-28 14:53 UTC
