### ISSUE TITLE
Executor vs ThreadFactory in Disruptor constructors

### ISSUE THREAD

**Issue by remkop** [LMAX-Exchange/disruptor#148] opened 2016-02-18 17:12 UTC
Since version 3.3.3, the dsl Disruptor constructors taking an Executor have been deprecated in favour of new constructors that take a ThreadFactory.

In Log4j 2, we have a use case where we need to know the thread ID of the background (consumer) thread. This is to prevent deadlocks when the object that was logged itself performs additional logging in its toString() method when the ring buffer is full.

With the Executor we were able to do this by scheduling a Callable that returns the thread ID at initialization time, but with ThreadFactory this will become more clunky.

Are there any plans to actually remove the Disruptor constructors that take an Executor? I would prefer to keep using these constructors...

Please advise.

Remko Popma

**Comment by mikeb01** [comment] 2016-02-18 20:19
You should be able to capture the thread id if you implement the LifecycleAware interface in your EventHandler.  You will get called back as soon as the thread starts.

Let me know how that works for you.  I won't drop the deprecated constructors until any user issues caused by using a ThreadFactory are ironed out.

The reason for moving to ThreadFactory insteads of Executor is that an Executor is not really the right abstraction.  Control over the number of threads required is set by the Disruptor, but many Executor implementations specify this themselves.  A common error for new starters is that they have 2 event handlers and pass a SingleThreadedExecutorService to the DSL.

**Comment by remkop** [comment] 2016-02-21 15:15
That should do the trick. Thanks for the advice! I'll let you know when it's done.

**Comment by mikeb01** [comment] 2016-04-18 21:11
The number of consumers is dictated by the number of handlers that you create.  With an Executor if not enough threads were allowed the Disruptor would simply hang without useful explanation.  So the "one producer one consumer" thing is orthogonal to using ThreadFactories over Executors.

If you want to prevent the creation of more than one consumer thread, then it is pretty easy to write a custom ThreadFactory that provides that restriction and will fail in a meaningful way.

```Java
public class LimitedThreadFactory implements ThreadFactory
{
    private final AtomicInteger count == new AtomicInteger(0);

    public Thread newThread(Runnable r)
    {
        if (count.compareAndSet(0, 1))
        {
            return new Thread(r);
        }
        else
        {
            throw new IllegalStateException("Created more that one thread");
        }
    }
}
```

**Comment by ivolnov** [comment] 2016-04-19 14:42
Thank you, but then I don't get it...

When you see a constructor with an Executor you think: "OK, framework wants me to provide a pool to execute consumers' jobs". And if you want all produced events to be handled by one thread you intuitively pass a single threaded implementation to control it. With event factory I might pass like 
`(ThreadFactory) Thread::new,` 
- no problem, but then it is not transparent what framework is planning to do with it.

According to:
`    public Disruptor(
            final EventFactory<T> eventFactory,
            final int ringBufferSize,
            final ThreadFactory threadFactory,
            final ProducerType producerType,
            final WaitStrategy waitStrategy)
    {
        this(RingBuffer.create(
                               producerType, eventFactory, ringBufferSize, waitStrategy),
                new BasicExecutor(threadFactory));
    }`
we basically have straightforward implementation of Executor that creates a single thread on every execute() call:
`package com.lmax.disruptor.dsl;

import java.util.concurrent.Executor;
import java.util.concurrent.ThreadFactory;

public class BasicExecutor implements Executor
{
    private final ThreadFactory factory;

    public BasicExecutor(ThreadFactory factory)
    {
        this.factory = factory;
    }

    @Override
    public void execute(Runnable command)
    {
        final Thread thread = factory.newThread(command);
        if (null == thread)
        {
            throw new RuntimeException("Failed to create thread to run: " + command);
        }

        thread.start();
    }
}`
and I have difficulties to estimate when this execute() is called...

Custom ThreadFactory that throws an Exception in case of multiple creations just gives me knowledge about a failed attempt but doesn't allow me to control the pool size...

Does it mean that by passing only one handler to disruptor's:

`    public EventHandlerGroup<T> handleEventsWith(final EventHandler<? super T>... handlers)
    {
        return createEventProcessors(new Sequence[0], handlers);
    }`

it results in a creation of only one thread?
I'm confused...

**Comment by mikeb01** [comment] 2016-04-19 21:09
The Disruptor requires 1 thread per EventProcessor/EventHandler.  One quite common bug is that someone would create a single threaded executor and create a Disruptor with 2 event handlers.  In that case the Disruptor would hang indefinitely at start up.  The idea that "OK, framework wants me to provide a pool to execute consumers jobs" for the Disruptor is the wrong.  What the Disruptor actually wants is to create a number of new threads (one per EventProcessor), which will be owned for the lifetime of the Disruptor.  In this case a ThreadFactory better describes what the Disruptor is intending to do (i.e. create threads).

The reason why a BasicExecutor is constructed internally is that I needed to preserve backwards compatibility.  Using an Executor is deprecated, but still works.  I didn't want to have 2 separate code paths and it is easy to make a ThreadFactory behave like a Executor, but difficult to do the inverse.

The BasicExecutor and support for passing in an Executor will be removed on the next major release (version 4).

**Closed by mikeb01** 2016-04-19 21:09 UTC

**Comment by ivolnov** [comment] 2016-04-19 21:29
Thank you, Mike, the behavior is clear now. Hopefully wiki will be updated too.

**Comment by hangc0276** [comment] 2023-12-12 15:42
In my system, one process has multiple disruptor instances and I want to limit the total threads that are created by those disruptor instances. One idea is to use an Executor thread pool. Would you give me some suggestions?
